COLUMNS = ['Gender_F',
           'Gender_M',
           'Gender_other',
           'Gender_queer',
           'Gender_trans',
           'self_employed_No',
           'self_employed_Yes',
           'family_history_No',
           'family_history_Yes',
           'treatment_No',
           'treatment_Yes',
           'no_employees_1-25',
           'no_employees_100-500',
           'no_employees_26-100',
           'no_employees_500-1000',
           'no_employees_More than 1000',
           'remote_work_No',
           'remote_work_Yes',
           'tech_company_No',
           'tech_company_Yes',
           "benefits_Don't know",
           'benefits_No',
           'benefits_Yes',
           'care_options_No',
           'care_options_Not sure',
           'care_options_Yes',
           "wellness_program_Don't know",
           'wellness_program_No',
           'wellness_program_Yes',
           "seek_help_Don't know",
           'seek_help_No',
           'seek_help_Yes',
           "anonymity_Don't know",
           'anonymity_No',
           'anonymity_Yes',
           "leave_Don't know",
           'leave_Somewhat difficult',
           'leave_Somewhat easy',
           'leave_Very difficult',
           'leave_Very easy',
           'mental_health_consequence_Maybe',
           'mental_health_consequence_No',
           'mental_health_consequence_Yes',
           'coworkers_No',
           'coworkers_Some of them',
           'coworkers_Yes',
           'supervisor_No',
           'supervisor_Some of them',
           'supervisor_Yes',
           'mental_health_interview_Maybe',
           'mental_health_interview_No',
           'mental_health_interview_Yes',
           "mental_vs_physical_Don't know",
           'mental_vs_physical_No',
           'mental_vs_physical_Yes',
           'obs_consequence_No',
           'obs_consequence_Yes',
           'Age']
